try-catch文による例外処理
